<?php

/**
 * @file ting_covers_extra.module
 *
 * Provides:
 * - plugins for retrieving covers for Ting objects and collections from additional cover providers
 * - extra standard covers and interface for administering them
 */


/**
 * Function to call all extra covers sources that have been defined.
 *
 * The array $missing_images_local_ids is modified to include
 * additional image URLs to external sources.
 *
 * @param array $missing_images_local_ids (by reference)
 * @param array $covers (by reference)
 * @param array $image_styles;
 */
function ting_covers_extra_get_image_urls(&$missing_images_local_ids, &$covers, $image_styles) {
  $sources = module_invoke_all('ting_covers_extra_sources');

  // Calls to external image sources for specific sources
  foreach ($missing_images_local_ids as $local_id_key => $local_id) {

    // Danske Billeder source
    if ($local_id->sourceName == 'Danske-Billeder') {
      $covers[] = array(
        'local_id' => $local_id->localIdentifier,
        'image_style' => $image_styles[$local_id->localIdentifier],
        'url' => ting_covers_extra_cover_url_dkbilleder($local_id),
      );

      // Remove from missing images array so ADDI service won't call it later
      unset($missing_images_local_ids[$local_id_key]);
    }

    // Historisk Atlas source
    if ($local_id->sourceName == 'Historisk-Atlas') {
      $covers[] = array(
        'local_id' => $local_id->localIdentifier,
        'image_style' => $image_styles[$local_id->localIdentifier],
        'url' => ting_covers_extra_cover_url_histatlas($local_id),
      );

      // Remove from missing images array so ADDI service won't call it later
      unset($missing_images_local_ids[$local_id_key]);
    }

    // DLB Vejle sources
    if ($local_id->sourceName == '630-01') {
      $covers[] = array(
        'local_id' => $local_id->localIdentifier,
        'image_style' => $image_styles[$local_id->localIdentifier],
        'url' => ting_covers_extra_cover_url_dlb_vejle($local_id),
      );

      // Remove from missing images array so ADDI service won't call it later
      unset($missing_images_local_ids[$local_id_key]);
    }
  }

  // Reset array index before traversing it again
  reset($missing_images_local_ids);
}


/**
 * Declares information about extra cover sources for ting objects and collections.
 *
 * Any module can declare additional cover providers by implementing this hook.
 *
 * @return
 * An associative array of cover source information. The keys of the array
 * are the names of the action functions, and each corresponding value
 * is an associative array with the following key-value pairs:
 * - 'type': The type of object this action acts upon. Core actions have types
 * 'node', 'user', 'comment', and 'system'.
 * - 'label': The human-readable name of the action, which should be passed
 * through the t() function for translation.
 */
function hook_ting_covers_extra_sources() {
  return array(
    'histatlas' => array(
      'sourcelabel' => 'Historisk-Atlas',
      'function' => 'ting_covers_extra_cover_url_histatlas',
    ),
    'dkbilleder' => array(
      'sourcelabel' => 'Danske-Billeder',
      'function' => 'ting_covers_extra_cover_url_dkbilleder',
    ),
    'dlb_vejle' => array(
      'sourcelabel' => 'Vejle-Stadsarkiv',
      'function' => 'ting_covers_extra_cover_url_dlb_vejle',
    ),
  );
}

/**
 * Function to get cover URL from provider Historisk Atlas
 *
 * @param object $local_id: is a 2-part identifier containing $local_id->libraryCode and $local_id->localIdentifier
 * @return string: url to image from Historisk Atlas
 */
function ting_covers_extra_cover_url_histatlas($local_id) {
  // Call the well with agency (ex. 763000) and the 2-part identifier (owner_id:local_id, eks. 150043:3802)
  require_once drupal_get_path('module', 'ting') . '/ting.client.inc';

  $request = ting_get_request_factory()->getObjectRequest();

  if ($agency = variable_get('ting_agency', FALSE)) {
    $request->setAgency($agency);
  }

  $profile = variable_get('ting_search_profile', '');
  if (!empty($profile) && method_exists($request, 'setProfile')) {
    $request->setProfile($profile);
  }

  // The identifier is libraryCode (aka owner_id) + local ID
  $request->setObjectId($local_id->libraryCode . ':' . $local_id->localIdentifier);
  $request->setFormat('opensearchobject');
  $request->setObjectFormat('opensearchobject');
  $request->setAllRelations('true');
  $request->setRelationData('full');
  // Set to PHP output instead of JSON to retrieve the relations - in JSON they are not present
  $request->setOutputType('php');

  $histatlas_result = ting_execute_cache($request);

  // Get URL to image from Historisk Atlas
  $histatlas_url = unserialize($histatlas_result)->searchResponse->_value->result->_value->searchResult[0]->_value->collection->_value->object[0]->_value->relations->_value->relation[1]->_value->relationObject->_value->object->_value->object->_value->image->_value;

  if (!empty($histatlas_url)) {
    $histatlas_url = $histatlas_url . '?width=200';
  }
  else {
    //TODO: get default from settings instead
    $histatlas_url = $GLOBALS['base_url'] . '/sites/default/files/ting_covers_defaults/histatlas.jpg';
  }

  // TODO: Try to download the image locally.

  return $histatlas_url;
}


/**
 * Function to get cover URL from provider Danske Billeder
 *
 * @param object $local_id: is a 2-part identifier containing $local_id->libraryCode and $local_id->localIdentifier
 * @return string: url to image from Danske Billeder
 */
function ting_covers_extra_cover_url_dkbilleder($local_id) {
  // Call the well with agency (ex. 763000) and the 2-part identifier (owner_id:local_id, eks. 150043:3802)
  require_once drupal_get_path('module', 'ting') . '/ting.client.inc';

  $request = ting_get_request_factory()->getObjectRequest();

  if ($agency = variable_get('ting_agency', FALSE)) {
    $request->setAgency($agency);
  }

  $profile = variable_get('ting_search_profile', '');
  if (!empty($profile) && method_exists($request, 'setProfile')) {
    $request->setProfile($profile);
  }

  // The identifier is libraryCode (aka owner_id) + local ID
  $request->setObjectId($local_id->libraryCode . ':' . $local_id->localIdentifier);
  $request->setFormat('opensearchobject');
  $request->setObjectFormat('opensearchobject');
  $request->setAllRelations('true');
  $request->setRelationData('full');
  // Set to PHP output instead of JSON to retrieve the relations - in JSON they are not present
  $request->setOutputType('php');

  $dkbilleder_result = ting_execute_cache($request);

  // Get URL to image from Danske Billeder
  $dkbilleder_url = unserialize($dkbilleder_result)->searchResponse->_value->result->_value->searchResult[0]->_value->collection->_value->object[0]->_value->relations->_value->relation[1]->_value->relationObject->_value->object->_value->object->_value->image->_value;

  if (!empty($dkbilleder_url)) {
    $dkbilleder_url = $dkbilleder_url;
  }
  else {
    //TODO: get default from settings instead
    $dkbilleder_url = $GLOBALS['base_url'] . '/sites/default/files/ting_covers_defaults/dkbilleder.jpg';
  }

  // TODO: Try to download the image locally.

  return $dkbilleder_url;
}


/**
 * Function to get cover URL from provider DLB Vejle (Dansk Lokalbibliografi Vejle)
 *
 * @param object $local_id: is a 2-part identifier containing $local_id->libraryCode and $local_id->localIdentifier
 * @return string: url to image from DLB Vejle
 */
function ting_covers_extra_cover_url_dlb_vejle($local_id) {
  /*
  // Call the well with agency (ex. 763000) and the 2-part identifier (owner_id:local_id, eks. 150043:3802)
  require_once drupal_get_path('module', 'ting') . '/ting.client.inc';

  $request = ting_get_request_factory()->getObjectRequest();

  if ($agency = variable_get('ting_agency', FALSE)) {
    $request->setAgency($agency);
  }

  $profile = variable_get('ting_search_profile', '');
  if (!empty($profile) && method_exists($request, 'setProfile')) {
    $request->setProfile($profile);
  }

  // The identifier is libraryCode (aka owner_id) + local ID
  $request->setObjectId($local_id->libraryCode . ':' . $local_id->localIdentifier);
  $request->setFormat('opensearchobject');
  $request->setObjectFormat('opensearchobject');
  $request->setAllRelations('true');
  $request->setRelationData('full');
  // Set to PHP output instead of JSON to retrieve the relations - in JSON they are not present
  $request->setOutputType('php');

  $dlb_vejle_result = ting_execute_cache($request);

  // Get URL to image from DLB Vejle
  $dlb_vejle_url = unserialize($dlb_vejle_result)->searchResponse->_value->result->_value->searchResult[0]->_value->collection->_value->object[0]->_value->relations->_value->relation[1]->_value->relationObject->_value->object->_value->object->_value->image->_value;
  */

  if (!empty($dlb_vejle_url)) {
    $dlb_vejle_url = $dlb_vejle_url;
  }
  else {
    //TODO: get default from settings instead
    $dlb_vejle_url = $GLOBALS['base_url'] . '/sites/default/files/ting_covers_defaults/dlb_vejle.png';
  }

  // TODO: Try to download the image locally.

  return $dlb_vejle_url;
}

